### ISSUE TITLE
Unable to create new user

### ISSUE THREAD

**Issue by svassell** [ngageoint/MapCache-server#3]
Hello,

I am trying to setup a working instance of the develop branch of mapcache-server but am unable to as when I go to create a new user I receive the two following errors:

(1) In the browser
Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.14/$rootScope/inprog?p0=%24apply
    at angular.js:63
    at beginPhase (angular.js:14755)
    at Scope.$apply (angular.js:14499)
    at progress (signin.controller.js:33)
    at user.service.js:201
    at Scope.$eval (angular.js:14401)
    at Scope.$apply (angular.js:14500)
    at XMLHttpRequestUpload.<anonymous> (user.service.js:200)
POST http://localhost:4242/api/users 500 (Internal Server) 

(2) In the terminal
2016-10-17T20:38:48.085Z - error: (mongoose/lib/drivers/node-mongodb-native/collection.js:125) Mongoose: roles.findOne({ name: 'USER_ROLE' }) { fields: undefined }  
2016-10-17T20:38:48.088Z - error: (express/lib/application.js:570) TypeError: Cannot read property '_id' of null
    at /home/geolab/Projects/mapcache-server-develop/routes/users.js:263:36
    at Layer.handle [as handle_request](/home/geolab/Projects/mapcache-server-develop/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/geolab/Projects/mapcache-server-develop/node_modules/express/lib/router/route.js:100:13)
    at validateUser (/home/geolab/Projects/mapcache-server-develop/routes/users.js:104:5)
    at Layer.handle [as handle_request](/home/geolab/Projects/mapcache-server-develop/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/geolab/Projects/mapcache-server-develop/node_modules/express/lib/router/route.js:100:13)
    at /home/geolab/Projects/mapcache-server-develop/routes/users.js:35:7
    at Promise.<anonymous> (/home/geolab/Projects/mapcache-server-develop/node_modules/mapcache-models/role.js:80:5)
    at Promise.<anonymous> (/home/geolab/Projects/mapcache-server-develop/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:107:17)
    at Promise.emit (/home/geolab/Projects/mapcache-server-develop/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/home/geolab/Projects/mapcache-server-develop/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Immediate.cb (/home/geolab/Projects/mapcache-server-develop/node_modules/mongoose/lib/query.js:1150:30)
    at Immediate._onImmediate (/home/geolab/Projects/mapcache-server-develop/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback](timers.js:367:17)

**Comment by danielbarela** [comment]
I believe the mongo migrate script was not run prior to running the server.
